version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
    commit-message:
      prefix: build
      include: scope
