version: "3"

services:
    db:
        image: mysql:8.0.23
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "./var/mysql:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: toytoc
            MYSQL_USER: toytoc
            MYSQL_PASSWORD: toytoc
        ports:
            - 3306:3306
        networks:
            - symfony
    php:
        build:
            context: ./docker/php
            args:
                TIMEZONE: Europe/Paris
        volumes:
            - ./:/var/www/symfony/
        networks:
            - symfony
    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./:/var/www/symfony/
        ports:
            - 80:80
        networks:
            - symfony
        env_file:
            - ./docker/.env.nginx

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

networks:
    symfony:

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
