version: "3"

services:
    db:
        image: mysql:8.0.23
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "./var/mysql:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: toytoc
            MYSQL_USER: toytoc
            MYSQL_PASSWORD: toytoc
        ports:
            - 3306:3306
        networks:
            - symfony
    php:
        build:
            context: ./docker/php
            args:
                TIMEZONE: Europe/Paris
        volumes:
            - ./:/var/www/symfony/
        networks:
            - symfony
    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./:/var/www/symfony/
        ports:
            - 80:80
        networks:
            - symfony
        env_file:
            - ./docker/.env.nginx

networks:
    symfony:
