admin_controllers:
    resource:
        path: ../src/Controller/Backoffice
        namespace: App\Controller\Backoffice
    type: attribute
    prefix: /admin

user_controllers:
    resource:
        path: ../src/Controller/Frontoffice
        namespace: App\Controller\Frontoffice
    type: attribute
    prefix: /home



